"""
Django settings for english_lessons project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-m2)46&bo48obqlp*o_y5z)rn+44*pl$q2h&wnho8pqo)tf-r*@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0', '*'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lessons',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'english_lessons.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'english_lessons.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Try to use PostgreSQL, fallback to SQLite if not available
USE_POSTGRES = env.bool('USE_POSTGRES', default=True)

if USE_POSTGRES:
    try:
        # Test PostgreSQL connection with longer timeout
        import psycopg2
        test_conn = psycopg2.connect(
            host=env('DB_HOST', default='localhost'),
            port=env('DB_PORT', default='5432'),
            user=env('DB_USER', default='postgres'),
            password=env('DB_PASSWORD', default=''),
            database=env('DB_NAME', default='english_lessons'),
            connect_timeout=10  # Увеличиваем timeout до 10 секунд
        )
        test_conn.close()
        
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env('DB_NAME', default='english_lessons'),
                'USER': env('DB_USER', default='postgres'),
                'PASSWORD': env('DB_PASSWORD', default=''),
                'HOST': env('DB_HOST', default='localhost'),
                'PORT': env('DB_PORT', default='5432'),
                'CONN_MAX_AGE': 600,  # Keep connections alive
                'OPTIONS': {
                    'connect_timeout': 10,
                    'options': '-c statement_timeout=30000'  # 30 секунд на выполнение запроса
                },
            }
        }
        import logging
        logger = logging.getLogger(__name__)
        logger.info('✓ PostgreSQL connection successful')
    except Exception as e:
        # Fallback to SQLite if PostgreSQL is not available
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f'PostgreSQL not available ({str(e)}), using SQLite instead')
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'lessons' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenRouter AI Settings
OPENROUTER_API_KEY = env('OPENROUTER_API_KEY', default='')
OPENROUTER_MODEL = env('OPENROUTER_MODEL', default='openai/gpt-4o-mini')
OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions'
# Использовать двухэтапный процесс (анализ + формирование карточек)
USE_TWO_STAGE_PROCESS = env.bool('USE_TWO_STAGE_PROCESS', default=True)

# Video Processing Settings
# На сервере используем /tmp для временных файлов и отдельную папку для загруженных видео
if os.path.exists('/tmp'):
    # Сервер (Linux)
    WATCHED_VIDEO_DIRECTORY = env('WATCHED_VIDEO_DIRECTORY', default='/var/www/english_lessons/uploads/videos')
    TEMP_AUDIO_DIRECTORY = env('TEMP_AUDIO_DIRECTORY', default='/tmp/english_lessons_audio')
else:
    # Локальная разработка (Windows)
    WATCHED_VIDEO_DIRECTORY = env('WATCHED_VIDEO_DIRECTORY', default=str(BASE_DIR / 'videos'))
    TEMP_AUDIO_DIRECTORY = env('TEMP_AUDIO_DIRECTORY', default=str(BASE_DIR / 'temp_audio'))

# Создаем директории, если их нет (с обработкой ошибок прав доступа)
try:
    os.makedirs(WATCHED_VIDEO_DIRECTORY, exist_ok=True)
except PermissionError:
    # Если нет прав, логируем предупреждение, но не прерываем запуск
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f'Не удалось создать директорию {WATCHED_VIDEO_DIRECTORY}. Создайте её вручную с sudo.')

try:
    os.makedirs(TEMP_AUDIO_DIRECTORY, exist_ok=True)
except PermissionError:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning(f'Не удалось создать директорию {TEMP_AUDIO_DIRECTORY}. Создайте её вручную.')

# Whisper Model Settings
WHISPER_MODEL = env('WHISPER_MODEL', default='base')

# FFmpeg Settings
# По умолчанию используем 'ffmpeg' из PATH, но можно указать полный путь в .env
FFMPEG_BINARY = env('FFMPEG_BINARY', default='ffmpeg')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Logging configuration: выводим логи в консоль во время разработки
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{levelname}] {asctime} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
            'stream': 'ext://sys.stdout',
        },
        'interface': {
            'class': 'lessons.services.log_handler.InterfaceLogHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'lessons': {
            'handlers': ['console', 'interface'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
