# Generated by Django 5.0.1 on 2025-12-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('transcript_text', models.TextField(verbose_name='Транскрипт урока')),
                ('language_level', models.CharField(choices=[('A0', 'A0 - Начальный'), ('A1', 'A1 - Элементарный'), ('A2', 'A2 - Ниже среднего'), ('B1', 'B1 - Средний'), ('B2', 'B2 - Выше среднего')], default='A1', max_length=10, verbose_name='Уровень языка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, unique=True, verbose_name='Путь к файлу')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('done', 'Обработано'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Видеофайл',
                'verbose_name_plural': 'Видеофайлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('repeat', 'Повторить'), ('translate', 'Перевести'), ('choose', 'Выбрать вариант'), ('color', 'Цвет'), ('speak', 'Проговорить'), ('match', 'Сопоставить')], max_length=20, verbose_name='Тип карточки')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('prompt_text', models.TextField(verbose_name='Инструкция для ребёнка')),
                ('correct_answer', models.TextField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Варианты ответов')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Карточка упражнения',
                'verbose_name_plural': 'Карточки упражнений',
                'ordering': ['lesson', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.videofile', verbose_name='Видеофайл'),
        ),
    ]
