# Generated by Django 5.0.1 on 2025-12-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='has_transcript',
            field=models.BooleanField(default=False, verbose_name='Транскрипт сохранён'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='transcript_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу транскрипта'),
        ),
    ]
