# Generated by Django 5.0.1 on 2025-12-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_videofile_has_transcript_videofile_transcript_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='raw_ai_response',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой ответ ИИ (JSON)'),
        ),
    ]
