# Generated by Django 5.0.1 on 2025-12-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_raw_ai_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии пользователя')),
                ('total_experience', models.IntegerField(default=0, verbose_name='Общий опыт')),
                ('current_level', models.IntegerField(default=1, verbose_name='Текущий уровень')),
                ('total_cards_completed', models.IntegerField(default=0, verbose_name='Всего карточек пройдено')),
                ('total_lessons_completed', models.IntegerField(default=0, verbose_name='Всего уроков пройдено')),
                ('correct_answers_count', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('incorrect_answers_count', models.IntegerField(default=0, verbose_name='Неправильных ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'ordering': ['-total_experience'],
            },
        ),
        migrations.AddField(
            model_name='exercisecard',
            name='hint_text',
            field=models.TextField(blank=True, help_text='Показывается после нескольких неправильных попыток', null=True, verbose_name='Текст подсказки'),
        ),
        migrations.AddField(
            model_name='exercisecard',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Название иконки из библиотеки (например: sun, cloud, dog, cat)', max_length=100, null=True, verbose_name='Название иконки/пиктограммы'),
        ),
        migrations.AddField(
            model_name='exercisecard',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AddField(
            model_name='exercisecard',
            name='translation_text',
            field=models.TextField(blank=True, null=True, verbose_name='Перевод для показа после правильного ответа'),
        ),
        migrations.CreateModel(
            name='LessonAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено'), ('abandoned', 'Прервано')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('score', models.FloatField(blank=True, help_text='Процент правильных ответов', null=True, verbose_name='Оценка (0-100)')),
                ('correct_cards', models.IntegerField(default=0, verbose_name='Правильных карточек')),
                ('total_cards', models.IntegerField(default=0, verbose_name='Всего карточек')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.lesson', verbose_name='Урок')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attempts', to='lessons.userprogress', verbose_name='Прогресс пользователя')),
            ],
            options={
                'verbose_name': 'Попытка прохождения урока',
                'verbose_name_plural': 'Попытки прохождения уроков',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CardAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, null=True, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('attempts_count', models.IntegerField(default=1, verbose_name='Количество попыток')),
                ('hint_shown', models.BooleanField(default=False, verbose_name='Показана подсказка')),
                ('experience_gained', models.IntegerField(default=0, verbose_name='Получено опыта')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.exercisecard', verbose_name='Карточка')),
                ('lesson_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_attempts', to='lessons.lessonattempt', verbose_name='Попытка урока')),
            ],
            options={
                'verbose_name': 'Попытка ответа на карточку',
                'verbose_name_plural': 'Попытки ответов на карточки',
                'ordering': ['answered_at'],
            },
        ),
    ]
