# Generated by Django 5.0.1 on 2025-12-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_userprogress_exercisecard_hint_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecard',
            name='card_type',
            field=models.CharField(choices=[('repeat', 'Повторить'), ('translate', 'Перевести'), ('choose', 'Выбрать вариант'), ('color', 'Цвет'), ('speak', 'Проговорить'), ('match', 'Сопоставить'), ('spelling', 'Написание'), ('new_words', 'Новые слова'), ('writing', 'Письмо')], max_length=20, verbose_name='Тип карточки'),
        ),
    ]
