# Generated by Django 5.0.1 on 2025-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_exercisecard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecard',
            name='topic',
            field=models.CharField(blank=True, help_text='Тема урока, к которой относится карточка (например: weather, actions, colors)', max_length=100, null=True, verbose_name='Тема карточки'),
        ),
    ]
