# Generated by Django 5.0.1 on 2025-12-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_exercisecard_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardattempt',
            name='card_status',
            field=models.IntegerField(default=0, help_text='0=красный (не пройдено), 3=желтый (с ошибками), 5=зеленый (идеально)', verbose_name='Статус карточки'),
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(default='Ученик', max_length=100, verbose_name='Имя персонажа')),
                ('avatar_emoji', models.CharField(default='🎓', max_length=10, verbose_name='Эмодзи персонажа')),
                ('total_score', models.FloatField(default=0.0, help_text='Средний балл по всем карточкам (0-5)', verbose_name='Средний балл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='lessons.userprogress', verbose_name='Прогресс пользователя')),
            ],
            options={
                'verbose_name': 'Персонаж пользователя',
                'verbose_name_plural': 'Персонажи пользователей',
                'ordering': ['-total_score'],
            },
        ),
    ]
