# Generated by Django 5.0.1 on 2025-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_cardattempt_card_status_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecard',
            name='is_repetition_card',
            field=models.BooleanField(default=False, help_text='Отмечено, если карточка создана для повторения из предыдущих уроков', verbose_name='Карточка для повторения'),
        ),
    ]
