# Generated by Django 5.0.1 on 2025-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_exercisecard_is_repetition_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='processing_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об обработке'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='processing_status',
            field=models.CharField(default='idle', help_text='idle, transcribing, generating_lesson, done, error', max_length=50, verbose_name='Статус обработки'),
        ),
    ]
