# Generated by Django 5.0.1 on 2025-12-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_videofile_processing_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код достижения')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('requirement_type', models.CharField(help_text='lessons_completed, perfect_score, streak_days, etc.', max_length=50, verbose_name='Тип требования')),
                ('requirement_value', models.IntegerField(default=1, verbose_name='Значение требования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата разблокировки')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.achievement', verbose_name='Достижение')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='lessons.userprogress', verbose_name='Прогресс пользователя')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user_progress', 'achievement')},
            },
        ),
    ]
