# Generated by Django 5.0.1 on 2025-12-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonattempt',
            name='stars',
            field=models.IntegerField(default=0, help_text='Количество звёзд: 1★ = 50-69%, 2★ = 70-99%, 3★ = 100%', verbose_name='Звёзды'),
        ),
    ]
